adlist/urls.py
from django.contrib import admin, auth
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('ads/', include('ads.urls'))

]


try:
    from adlist.settings import SOCIAL_AUTH_GITHUB_KEY
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth.views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except Exception as e:
    print('Using registration/login.html as the login template')

ads/urls.py
from django.urls import path 
from ads.views import AdCreateView, AdDeleteView, AdDetailView, AdListView, AdUpdateView

app_name = 'ads'
urlpatterns = [
    path('', AdListView.as_view(), name='all'),
    path('<int:pk>', AdDetailView.as_view(), name='ad_detail'),
    path('create', AdCreateView.as_view(), name='ad_create'),
    path('<int:pk>/update', AdUpdateView.as_view(), name='ad_update'),
    path('<int:pk>/delete', AdDeleteView.as_view(), name='ad_delete')
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings


class Ad(models.Model):
    title = models.CharField(max_length=200,
                             validators=[MinLengthValidator(2, "Title must be greater than 2 characters")])
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

ads/views.py
from django.shortcuts import render
from ads.owner import OwnerCreateView, OwnerListView, OwnerDeleteView, OwnerDetailView, OwnerUpdateView
from ads.models import Ad
from django.urls import reverse_lazy

# Create your views here.

class AdListView(OwnerListView):
    model = Ad 

class AdDetailView(OwnerDetailView):
    model = Ad 
    
class AdCreateView(OwnerCreateView):
    model = Ad 
    fields = ['title', 'text', 'price']
    success_url = reverse_lazy('ads:all')

class AdUpdateView(OwnerUpdateView):
    model = Ad 
    fields = ['title', 'text', 'price']
    success_url = reverse_lazy('ads:all')

class AdDeleteView(OwnerDeleteView):
    model = Ad 
    success_url = reverse_lazy('ads:all')

home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations


class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Article</h1>

<p>Are you sure you want to delete the ad: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}

{% block content %}
    {% if ad %}
        <h1>{{ ad.title }}</h1>
        <p>{{ ad.text }}</p>
        <p>{{ ad.price}}</p>

        {% if user == ad.owner %}
            (
                <a href="{% url 'ads:ad_update' ad.id%}">Edit</a> |
                <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>
            )
        {% endif %}
    {% else %}
            <p> The ad you are looking for is removed.</p>
    {% endif %}

    {% if user.is_authenticated %}
            <a href="{% url 'ads:ad_create' %}">Create Ad</a>
    {% endif %}
{% endblock %}

ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}

{% block content %}
    {% load crispy_forms_tags %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}

{% block content %}
    {% if ad_list %}
        {% for ad in ad_list %}
            <li>
                <a href="{% url 'ads:ad_detail' ad.id %}">{{ ad.title }}</a>
                {% if user == ad.owner %}
                    (
                        <a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
                        <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>
                    )
                {% endif %}
            </li>
        {% endfor %}
    {% else %}
            <p> There is no ads currently</p>
    {% endif %}

    {% if user.is_authenticated %}
            <a href="{% url 'ads:ad_create' %}">Create Ad</a>
    {% endif %}
{% endblock %}

ads/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'ads' as ads %}
      <li {% if request.get_full_path == ads %}class="active"{% endif %}>
          <a href="{% url 'ads:all' %}">Ads</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'ads:ad_create' %}">Create Ad</a>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="c50467ff8890db4ba10bce0a004acc88">

<meta name="dj4e-code" content="42168080158890">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2022-11-01">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/home/main.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>Welcome to {{ settings.APP_NAME }}</h1>
    <p>
    Hello world.
    </p>
{% endblock content %}